name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events 
  push:
    branches: [ master, configure-github-actions, dockerfile-only ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Build-and-run:
    # The type of runner that the job will run on
    runs-on: docker

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} 
      - name: Build docker image
        run:  docker build -t leukocyt/flask-app:${GITHUB_REF#refs/heads/} .
      - name: Push docker image
        run: docker image push leukocyt/flask-app:${GITHUB_REF#refs/heads/}
      - name: Clean containers
        run: if [ $(docker ps | grep 6001 | awk {'print $1'} | grep -vc grep > 0) ]; then docker kill $(docker ps -a | grep 6001 | awk {'print $1'}); else echo 'no containters'; fi 
      - name: Run container with app
        run:  docker run -d -p 6001:5001 leukocyt/flask-app:${GITHUB_REF#refs/heads/}
